# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Vurse' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Vurse

  target 'VurseTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Lock', '~> 1.24'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'

end
